Configure ntp servers earlier
metal-stack/metal-hammer pull request #149
Opened 2024-12-19 15:59 UTC by simcod

## Description

If a machine has the wrong time / date configured, there may be a problem with the time stamp of the certificate. To resolve this, the NTP server configuration should be done earlier.
This PR is related to [MEP14](https://docs.metal-stack.io/stable/development/proposals/MEP14/README/) and the possibility to configure self-deployed NTP servers for the metal-hammer.

2025-01-07 13:22 UTC, Gerrit91 commented
Did you try this out? Does it work?

2025-01-29 07:34 UTC, robertvolkmann approved these changes

2025-02-17 09:45 UTC, robertvolkmann requested changes

2025-02-17 09:45 UTC, robertvolkmann commented on main.go
> +	// Set Time from ntp
```suggestion
	// Synchronize time using NTP
```

2025-02-20 17:28 UTC, merged